# -*- coding: utf-8 -*-
"""「vectorbt.ipynb」的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h3lpRfJ-NEj6wHYp2a6_DlMxhj94yvoE
"""
"""
try:
    import vectorbt as vbt
except ImportError:
    !pip install -U vectorbt[full]
"""
import os
os.kill(os.getpid(), 9)

# multi_ticker_param_recommend.py
# -*- coding: utf-8 -*-
"""
Multi-ticker param-grid + next-day recommendation (BUY/SELL/HOLD) script
功能：
- 對多檔股票掃 MA_LENS x ATR_MULTS grid（MA 向量化）
- 取得每檔 Profit Factor 最高的組合 (best combo)
- 以 best combo 重建 signals（entries/exits/trail）
- 不論是否實際持倉，對每檔輸出「下一交易日建議」：BUY / SELL / HOLD / WAIT + 理由與建議止損或條件買單
輸出：
- param_grid_multi_results.csv (所有組合)
- per_ticker_best.csv (每檔最佳組合)
- recommendations.csv (建議)
- HTML 圖檔：每檔 heatmap & best combo price plot
"""
import os
import sys
import numpy as np
import pandas as pd
import vectorbt as vbt
import yfinance as yf
from tqdm import tqdm
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# -------------------- 使用者參數 (可調) --------------------
TICKERS = ["AAPL","NVDA","GOOG","VOO","TSLA","NFLX"]
START_DATE = "2024-01-01"
FREQ = "1d"

MA_LENS = [10,15,20,30,50]          # 可擴大成數十組
ATR_MULTS = [1.5,2.0,2.5,3.0]      # 可擴張

ATR_LEN = 14
LONG_MA_LEN = 200
USE_LONG_MA_FILTER = True

INIT_CASH = 800
COMMISSION = 0.002
SIZE_HACK_VALUE = 100000

OUT_DIR = "multi_param_outputs"
os.makedirs(OUT_DIR, exist_ok=True)
ALL_RESULTS_CSV = os.path.join(OUT_DIR, "param_grid_multi_results.csv")
BEST_CSV = os.path.join(OUT_DIR, "per_ticker_best.csv")
RECOMMEND_CSV = os.path.join(OUT_DIR, "recommendations.csv")

# -------------------- 小工具函式 --------------------
def safe_download_series(ticker, start, interval):
    """逐 ticker 下載 OHLC，回傳 open, high, low, close (pd.Series) 或 (None,...) 若失敗"""
    try:
        data = vbt.YFData.download(ticker, start=start, interval=interval)
    except Exception:
        try:
            df = yf.download(ticker, start=start, interval=interval, progress=False)
            data = df
        except Exception:
            return None, None, None, None

    def get_field(obj, key):
        if obj is None:
            return None
        if hasattr(obj, "get"):
            try:
                return obj.get(key)
            except Exception:
                pass
        if isinstance(obj, pd.DataFrame) and key in obj.columns:
            return obj[key]
        return None

    open_s = get_field(data, "Open")
    high_s = get_field(data, "High")
    low_s  = get_field(data, "Low")
    close_s= get_field(data, "Close")
    # fallback
    if close_s is None and isinstance(data, pd.DataFrame) and "Adj Close" in data.columns:
        close_s = data["Adj Close"]

    if close_s is None:
        return None, None, None, None

    close_s = pd.Series(close_s).dropna()
    # align other series
    if open_s is not None:
        open_s = pd.Series(open_s).reindex(close_s.index)
    if high_s is not None:
        high_s = pd.Series(high_s).reindex(close_s.index)
    if low_s is not None:
        low_s = pd.Series(low_s).reindex(close_s.index)
    return open_s, high_s, low_s, close_s

def try_attr(obj, names):
    """從 indicator run 的對象取常見屬性"""
    if isinstance(obj, (pd.Series, pd.DataFrame)):
        return obj
    for n in names:
        if hasattr(obj, n):
            return getattr(obj, n)
    try:
        return pd.Series(obj)
    except Exception as e:
        raise AttributeError(f"Indicator object missing {names}. Error: {e}")

def compute_in_position(entries, exits):
    """重放 entries/exits 得到當前是否在倉 & 最後入場時間"""
    in_pos = False
    last_entry_idx = None
    for idx in entries.index:
        if entries.loc[idx] and not in_pos:
            in_pos = True
            last_entry_idx = idx
        if exits.loc[idx] and in_pos:
            in_pos = False
            last_entry_idx = None
    return in_pos, last_entry_idx

# -------------------- 主流程 --------------------
all_results = []

print("Python:", sys.version.splitlines()[0])
print("vectorbt:", getattr(vbt, "__version__", "unknown"))
print("Tickers:", TICKERS)
print("MA_LENS:", MA_LENS, "ATR_MULTS:", ATR_MULTS)

for ticker in TICKERS:
    print(f"\n=== Processing {ticker} ===")
    open_s, high_s, low_s, close = safe_download_series(ticker, START_DATE, FREQ)
    if close is None or len(close) < 60:
        print(f"Skip {ticker}: no data or too short.")
        continue

    # prepare ATR and long MA
    atr_run = vbt.ATR.run(high_s, low_s, close, window=ATR_LEN)
    atr = try_attr(atr_run, ["atr","real","value","output"])
    if isinstance(atr, pd.DataFrame):
        atr = atr.iloc[:,0]
    atr = atr.reindex(close.index)

    if USE_LONG_MA_FILTER:
        long_ma_run = vbt.MA.run(close, window=LONG_MA_LEN, ewm=False)
        long_ma = try_attr(long_ma_run, ["ma","real","value","output"])
        if isinstance(long_ma, pd.DataFrame):
            long_ma = long_ma.iloc[:,0]
        long_ma = long_ma.reindex(close.index)
    else:
        long_ma = pd.Series(np.nan, index=close.index)

    # vectorized compute of multiple MAs
    ma_run = vbt.MA.run(close, window=MA_LENS, ewm=False)
    ma_all = try_attr(ma_run, ["ma","real","value","output"])
    if isinstance(ma_all, pd.Series):
        ma_all = ma_all.to_frame(name=str(MA_LENS[0]))
    # try to label columns
    try:
        if len(ma_all.columns) == len(MA_LENS):
            ma_all.columns = [str(int(w)) for w in MA_LENS]
    except Exception:
        pass

    # broadcast close
    close_df = pd.DataFrame(np.repeat(close.values[:,None], ma_all.shape[1], axis=1),
                            index=close.index, columns=ma_all.columns)
    entries_df = (close_df > ma_all) & (close_df.shift(1) <= ma_all.shift(1))
    entries_df = entries_df.fillna(False).astype(bool)
    if USE_LONG_MA_FILTER:
        long_df = pd.DataFrame(np.repeat(long_ma.values[:,None], ma_all.shape[1], axis=1), index=close.index, columns=ma_all.columns)
        entries_df &= (close_df > long_df)

    # iterate ATR multipliers & MA columns
    combos = len(ma_all.columns) * len(ATR_MULTS)
    print(f"Running {combos} combos for {ticker} ...")
    for atr_mult in tqdm(ATR_MULTS, desc=f"{ticker} ATRs"):
        for col in ma_all.columns:
            entries = entries_df[col]
            # compute exits via per-bar ATR trailing
            exits = pd.Series(False, index=close.index)
            trail = pd.Series(np.nan, index=close.index)
            in_pos_flag = False
            cur_trail = np.nan
            for i in range(1, len(close)):
                if pd.isna(ma_all[col].iloc[i]) or pd.isna(atr.iloc[i]):
                    continue
                if entries.iloc[i] and (not in_pos_flag):
                    in_pos_flag = True
                    cur_trail = close.iloc[i] - atr.iloc[i] * atr_mult
                    trail.iloc[i] = cur_trail
                elif in_pos_flag:
                    new_stop = close.iloc[i] - atr.iloc[i] * atr_mult
                    cur_trail = max(cur_trail, new_stop) if not np.isnan(cur_trail) else new_stop
                    trail.iloc[i] = cur_trail
                    if close.iloc[i] < cur_trail:
                        exits.iloc[i] = True
                        in_pos_flag = False
                        cur_trail = np.nan

            # run portfolio
            pf = vbt.Portfolio.from_signals(
                close=close,
                entries=entries,
                exits=exits,
                init_cash=INIT_CASH,
                fees=COMMISSION,
                size=SIZE_HACK_VALUE,
                direction="longonly",
                freq=FREQ
            )

            stats = pf.stats()
            # safe extraction
            pfactor = stats.get("Profit Factor") if "Profit Factor" in stats.index else stats.get("profit_factor", np.nan)
            total_return = stats.get("Total Return [%]") if "Total Return [%]" in stats.index else stats.get("total_return", np.nan)
            max_dd = stats.get("Max Drawdown [%]") if "Max Drawdown [%]" in stats.index else stats.get("max_drawdown", np.nan)
            n_trades = stats.get("Total Trades") if "Total Trades" in stats.index else stats.get("total_trades", 0)
            sharpe = stats.get("Sharpe ratio") if "Sharpe ratio" in stats.index else stats.get("sharpe", np.nan)

            try:
                ma_len_val = int(''.join(filter(str.isdigit, col)))
            except Exception:
                ma_len_val = col

            all_results.append({
                'ticker': ticker,
                'ma_col': col,
                'ma_len': ma_len_val,
                'atr_mult': float(atr_mult),
                'profit_factor': float(pfactor) if not pd.isna(pfactor) else np.nan,
                'total_return': float(total_return) if not pd.isna(total_return) else np.nan,
                'max_drawdown': float(max_dd) if not pd.isna(max_dd) else np.nan,
                'n_trades': int(n_trades) if not pd.isna(n_trades) else 0,
                'sharpe': float(sharpe) if not pd.isna(sharpe) else np.nan
            })

    # build and save per-ticker heatmap
    res_ticker = pd.DataFrame([r for r in all_results if r['ticker']==ticker])
    if not res_ticker.empty:
        try:
            res_ticker['ma_len'] = res_ticker['ma_len'].astype(int)
            pivot = res_ticker.pivot(index='ma_len', columns='atr_mult', values='profit_factor')
        except Exception:
            pivot = res_ticker.pivot(index='ma_col', columns='atr_mult', values='profit_factor')

        fig = px.imshow(pivot, labels=dict(x="atr_mult", y="ma_len", color="Profit Factor"),
                        x=[str(x) for x in pivot.columns], y=[str(y) for y in pivot.index],
                        title=f"{ticker} Profit Factor heatmap", text_auto=True)
        fig.update_layout(yaxis_autorange='reversed')
        html_path = os.path.join(OUT_DIR, f"{ticker}_heatmap.html")
        fig.write_html(html_path)
        print(f"Saved heatmap for {ticker} -> {html_path}")

# -------------------- 匯總所有結果並找出每檔最佳組合 --------------------
res_df = pd.DataFrame(all_results)
res_df.to_csv(ALL_RESULTS_CSV, index=False)
print(f"\nSaved all combos to {ALL_RESULTS_CSV}")

# 每檔 best combo (以 profit_factor 排序)
best_list = []
for ticker in res_df['ticker'].unique():
    sub = res_df[res_df['ticker']==ticker].copy()
    sub = sub.sort_values("profit_factor", ascending=False).reset_index(drop=True)
    if sub.shape[0] == 0:
        continue
    best = sub.iloc[0]
    best_list.append(best.to_dict())

best_df = pd.DataFrame(best_list)
best_df.to_csv(BEST_CSV, index=False)
print(f"Saved per-ticker best combos to {BEST_CSV}")

# -------------------- 針對每檔 best combo 生成「下一日建議」 --------------------
recommendations = []

for idx, row in best_df.iterrows():
    ticker = row['ticker']
    best_ma = int(row['ma_len'])
    best_atr = float(row['atr_mult'])
    print(f"\n--- Recommend for {ticker}: MA={best_ma}, ATRx{best_atr} ---")

    # reload price series for ticker (ensure aligned)
    open_s, high_s, low_s, close = safe_download_series(ticker, START_DATE, FREQ)
    if close is None or len(close) < 60:
        print(f"  Skip {ticker}: no data.")
        continue

    # recompute indicator for best_ma & atr
    atr_run = vbt.ATR.run(high_s, low_s, close, window=ATR_LEN)
    atr = try_attr(atr_run, ["atr","real","value","output"])
    if isinstance(atr, pd.DataFrame): atr = atr.iloc[:,0]
    atr = atr.reindex(close.index)

    ma_run = vbt.MA.run(close, window=best_ma, ewm=False)
    ma_series = try_attr(ma_run, ["ma","real","value","output"])
    if isinstance(ma_series, pd.DataFrame): ma_series = ma_series.iloc[:,0]
    ma_series = ma_series.reindex(close.index)

    if USE_LONG_MA_FILTER:
        long_ma_run = vbt.MA.run(close, window=LONG_MA_LEN, ewm=False)
        long_ma = try_attr(long_ma_run, ["ma","real","value","output"])
        if isinstance(long_ma, pd.DataFrame): long_ma = long_ma.iloc[:,0]
        long_ma = long_ma.reindex(close.index)
    else:
        long_ma = pd.Series(np.nan, index=close.index)

    # rebuild entries/exits/trail for best combo
    entries = (close > ma_series) & (close.shift(1) <= ma_series.shift(1))
    entries = entries.fillna(False).astype(bool)
    if USE_LONG_MA_FILTER:
        entries &= (close > long_ma)

    exits = pd.Series(False, index=close.index)
    trail = pd.Series(np.nan, index=close.index)
    in_pos_flag = False
    cur_trail = np.nan
    for i in range(1, len(close)):
        if pd.isna(ma_series.iloc[i]) or pd.isna(atr.iloc[i]):
            continue
        if entries.iloc[i] and (not in_pos_flag):
            in_pos_flag = True
            cur_trail = close.iloc[i] - atr.iloc[i] * best_atr
            trail.iloc[i] = cur_trail
        elif in_pos_flag:
            new_stop = close.iloc[i] - atr.iloc[i] * best_atr
            cur_trail = max(cur_trail, new_stop) if not np.isnan(cur_trail) else new_stop
            trail.iloc[i] = cur_trail
            if close.iloc[i] < cur_trail:
                exits.iloc[i] = True
                in_pos_flag = False
                cur_trail = np.nan

    # determine current status and suggestion (regardless of real holdings)
    in_pos_now, last_entry = compute_in_position(entries, exits)
    last_dt = close.index[-1]
    last_close = float(close.iloc[-1])
    ma_last = float(ma_series.iloc[-1]) if not pd.isna(ma_series.iloc[-1]) else None
    ma_prev = float(ma_series.iloc[-2]) if len(ma_series)>=2 and not pd.isna(ma_series.iloc[-2]) else None
    long_ma_last = float(long_ma.iloc[-1]) if ('long_ma' in locals() and not pd.isna(long_ma.iloc[-1])) else None
    last_trail = float(trail.dropna().iloc[-1]) if trail.dropna().shape[0]>0 else None

    action = "WAIT / CONDITIONAL BUY"
    reason = ""
    suggested_stop = None
    conditional_rule = None

    if in_pos_now:
        # 策略上目前在倉 -> HOLD 並給出 stop
        action = "HOLD"
        reason = f"Strategy indicates position open (last entry at {last_entry.date()})"
        if last_trail is not None:
            suggested_stop = last_trail
            reason += f"; current ATR trail = {last_trail:.2f}"
        else:
            reason += "; no trail available"
    else:
        # not in position
        if entries.iloc[-1]:
            action = "BUY (signal triggered today)"
            reason = "Today's close crossed above MA -> entry signal triggered at last close."
        else:
            # propose conditional buy rule
            action = "WAIT / CONDITIONAL BUY"
            reason = "No entry signal today."
            conditional_rule = f"Buy if next close > MA_today ({ma_last:.4f})"
            if not pd.isna(long_ma_last):
                conditional_rule += f" and next close > longMA ({long_ma_last:.4f})"

    recommendations.append({
        "ticker": ticker,
        "best_ma": best_ma,
        "best_atr_mult": best_atr,
        "profit_factor": row['profit_factor'],
        "last_date": str(last_dt.date()),
        "last_close": last_close,
        "in_strategy_position": bool(in_pos_now),
        "action": action,
        "reason": reason,
        "suggested_stop": suggested_stop,
        "conditional_rule": conditional_rule
    })

    # also produce price+signals plot for best combo and save html
    try:
        fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.08,
                            row_heights=[0.7, 0.3], specs=[[{}], [{"type":"heatmap"}]])
        fig.add_trace(go.Candlestick(x=close.index, open=open_s, high=high_s, low=low_s, close=close, name="Price"), row=1, col=1)
        fig.add_trace(go.Scatter(x=ma_series.index, y=ma_series.values, mode="lines", name=f"MA{best_ma}"), row=1, col=1)
        fig.add_trace(go.Scatter(x=trail.index, y=trail.values, mode="lines", name="ATR trail", line=dict(dash="dash")), row=1, col=1)
        fig.add_trace(go.Scatter(x=entries[entries].index, y=close.loc[entries[entries].index], mode="markers", name="Entry", marker=dict(symbol="triangle-up", size=7, color="green")), row=1, col=1)
        fig.add_trace(go.Scatter(x=exits[exits].index, y=close.loc[exits[exits].index], mode="markers", name="Exit", marker=dict(symbol="triangle-down", size=7, color="red")), row=1, col=1)

        # small heatmap showing profit_factor per ma_len (agg across atr) for this ticker
        res_ticker = res_df[res_df['ticker']==ticker]
        try:
            res_ticker['ma_len'] = res_ticker['ma_len'].astype(int)
            pivot = res_ticker.pivot(index='ma_len', columns='atr_mult', values='profit_factor')
        except Exception:
            pivot = res_ticker.pivot(index='ma_col', columns='atr_mult', values='profit_factor')
        heat_z = pivot.values
        heat_x = [str(x) for x in pivot.columns]
        heat_y = [str(y) for y in pivot.index]
        fig.add_trace(go.Heatmap(z=heat_z, x=heat_x, y=heat_y, colorbar=dict(title="Profit Factor")), row=2, col=1)

        html_path = os.path.join(OUT_DIR, f"{ticker}_best_combo.html")
        fig.write_html(html_path)
    except Exception as e:
        print(f"  Warning: could not save plot for {ticker}. Err: {e}")

# -------------------- 儲存 recommendations --------------------
rec_df = pd.DataFrame(recommendations)
rec_df.to_csv(RECOMMEND_CSV, index=False)
best_df.to_csv(BEST_CSV, index=False)
res_df.to_csv(ALL_RESULTS_CSV, index=False)

print(f"\nSaved all combos to {ALL_RESULTS_CSV}")
print(f"Saved per-ticker best combos to {BEST_CSV}")
print(f"Saved recommendations to {RECOMMEND_CSV}")
print("Done.")

import pandas as pd

rec = pd.read_csv("multi_param_outputs/recommendations.csv")

display(
    rec[["ticker","action","reason","profit_factor"]]
    .sort_values("profit_factor", ascending=False)
    .reset_index(drop=True)
)
